{% set name = "compass" %}
{% set version = "0.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/opera-adt/COMPASS/archive/v{{ version }}.tar.gz
  sha256: dd5f7e0c0e9535388f15cf4846342dc53b424a3477ea67c99358711c031055ac

build:
  entry_points:
    - s1_cslc.py = compass.s1_cslc:main
    - s1_geocode_stack.py = compass.s1_geocode_stack:main
    - s1_static_layers.py = compass.s1_static_layers:main
    - validate_product.py = compass.utils.validate_product:main
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0
    - pip >=21.3
  run:
    - python >=3.8
    - numpy >=1.20
    - gdal >=3.3
    - h5py >=3.5
    - isce3 >=0.14.0
    - pandas >=1.4
    - pyproj >=3.3
    - pillow >=7.0
    - pysolid >=0.3
    - requests >=2.0
    - ruamel.yaml >=0.15
    - s1reader >=0.2.0
    - scipy >=1.0,<1.13
    - scikit-image >=0.19
    - shapely >=1.8
    - yamale >=4.0


test:
  imports:
    - compass
    - compass.s1_geocode_slc
    - compass.s1_static_layers
    - compass.utils.lut
  commands:
    - s1_cslc.py --help
  requires:
    - pip

about:
  home: https://github.com/opera-adt/COMPASS
  summary: COregistered Multi-temPorAl Sar Slc
  description: |
    COMPASS is a package to create geocoded single-look-complex (SLC)
    radar images from Sentinel-1 data using isce3.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/opera-adt/COMPASS

extra:
  recipe-maintainers:
    - scottstanie
    - seongsujeong
    - vbrancat
    - LiangJYu
